apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth-service
        tier: frontend
    spec:
      containers:
      - name: oauth-service
        image: docker.astuart.co:5000/oidc/oauth-server-test
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: OAUTH_SERVER
          value: "https://mitreid.astuart.co/openid-connect-server"
        - name: OAUTH_CLIENT_ID
          value: 2f987cc1-0958-4e5a-9782-ad2dbd57599e
        - name: OAUTH_CLIENT_SECRET
          value: WxFsJP7PoxputvmEpXQwE3PRT9o4Rm7t1cskbOrA9Mumf1pc7eW6PXsIC8I6DGJA1BBW2uI7EiCU5QfIzaeVGA
        - name: ROOT_CA
          value: |
            -----BEGIN CERTIFICATE-----
            MIIDLzCCAhegAwIBAgIJALsD4dhjW9hAMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
            BAMMCVN0dWFydCBDQTAeFw0xNjAzMTMxOTM5MjBaFw0yNjAzMTExOTM5MjBaMBQx
            EjAQBgNVBAMMCVN0dWFydCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
            ggEBANbhNmArgIfJKSbh92o9lBxV2SoPshvdOvrTkmrHTuoDkPqWoTXUzaKaUTAH
            6t7wHTxoxWShHbQaohYwkdJa74DVEw3pkChr5jOCN4XkgKNv4JUkFSKoArBdFSMN
            QxtuYTgedumlwyFG7kAumE2wwiNA5t2tLNArZFJapks9iPyMbO5oCzXiWpn8/6KV
            OZXOnCYJsDcMfJ7Jq0lzRVU9y/mQYF8YndK23CTGegMGFsg0i8/2nmxogJFYC+hi
            Cd7+PnGp4usno+pVlHflBy25lkSx7Udq+5EMi6s7ebfezGFn2Ia0yvud8uMHDmuE
            UWehJfZrJj1dsaG+8Wo+N79/gm8CAwEAAaOBgzCBgDAdBgNVHQ4EFgQUtS0ilhtv
            JOcwwukbR54BryyTmfEwRAYDVR0jBD0wO4AUtS0ilhtvJOcwwukbR54BryyTmfGh
            GKQWMBQxEjAQBgNVBAMMCVN0dWFydCBDQYIJALsD4dhjW9hAMAwGA1UdEwQFMAMB
            Af8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQCaJYZ/4Y21Zl5c2POh
            mJgtWgay6SMxrjSo9CmcU3NMCWPlLOCSjJoXjlV99pebfiSPM2q762rLghOSEluN
            7v0H6MOnfQFrkwfcbctPZtgBDVq0uLnNdJWKoFVf/puLsalCATZyFaoayxZgorjh
            +csM51pgD0SHjSdmHdmweBCu5xOLJBq5o7ek5OxANf2msgLm97wFkrnC4/9lQxiZ
            LvOT5Q8e91FUqoVFd6d/ZQqzAcg49Neug4uvVQ0m9uFul1jsYXtO0zSHeshyHDCw
            YTf6BmFDa52efAb3F88mNwCpVTU1GGnWDv4THfqUbnN4nm3vvKMUVAnhk1SwgV4W
            AvQT
            -----END CERTIFICATE-----
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: oauth-service
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth-service
  namespace: default
spec:
  rules:
  - host: oauth-service.ci.astuart.co
    http:
      paths:
      - path: /
        backend:
          serviceName: oauth-service
          servicePort: 80
